parameters:
#    prode_main.example.class: Prode\MainBundle\Example

services:
#    prode_main.example:
#        class: %prode_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
  prode_user.registration.form.type:
        class: Prode\MainBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: prode_user_registration }
