services:
    sonata.admin.user:
        class: Prode\MainBundle\Admin\ProdeUserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Usuario" }
        arguments:
            - ~
            - Prode\MainBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [ProdeMainBundle]]

    sonata.admin.team:
        class: Prode\MainBundle\Admin\TeamAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Equipo" }
        arguments:
            - ~
            - Prode\MainBundle\Entity\Team
            - ~
        calls:
            - [ setTranslationDomain, [ProdeMainBundle]]    
            
    sonata.admin.game:
        class: Prode\MainBundle\Admin\GameAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Partido" }
        arguments:
            - ~
            - Prode\MainBundle\Entity\Game
            - ~
        calls:
            - [ setTranslationDomain, [ProdeMainBundle]]               